### ISSUE TITLE
bool handling in BoutOptions

### ISSUE THREAD

**Issue by johnomotani** [boutproject/boutdata#32]
At the moment we leave bool options as strings in BoutOptions. Failing to deal with this lead to a bug in xSTORM because `bool("false") == True`. I think we should deal with this in BoutOptions, although there's not a perfect answer because (i) BOUT++ can understand various expressions as bools (so it would be nice to convert all of them in one place) but (ii) if an option is read as a string in BOUT++ `"t"` and `"f"`, etc., might be desired values and there's no way to know just from the input file if the option should be a bool or a string.

Options I can think of:
1. Automatically convert anything BOUT++ can interpret as a bool into a bool
    * probably the most convenient, and usually correct, but would make it a pain to deal with the edge case where the bool-like value should actually be kept as a string
2. Leave the current behaviour of keeping everything that's not an int or float as a string
    * fine for loading/editing/re-writing input files, but inconvenient if you want to use the values in Python
3. Add a method like `get_bool()` that converts strings to bools in the same way as BOUT++, and raises an exception if the string is wrong
    * less convenient than 1, but allows handling the edge case

3 seems like the best option to me - I'll make a PR (should be fairly simple I hope) - but opinions would be welcome.
@ZedThree @bendudson

**Comment by johnomotani** [comment]
I just checked the BOUT++ code, and BOUT++ converts any string starting with y, Y, t, T or 1 to `True` and n, N, f, F or 0 to `False`, so option 1 isn't really nice - we could only really allow a subset of strings that BOUT++ could convert to bool because it would be ridiculous to automatically convert `"foo"` to `False`, etc. Confirms option 3 as the best choice I think.

**Comment by dschwoerer** [comment]
Another option would be to subclass a string, so that the `__bool__` operator.

And while we are at it maybe also `__int__` and `__float__` so we could keep the exact values and only convert as needed, although that might be a breaking change, because `float()` or `int()` need to be called explicitly.

**Comment by johnomotani** [comment]
Interesting thought @dschwoerer. We could make something that mirrors the behaviour of the `Options` in BOUT++ with variant types, which would be pretty cool. If we made it a separate type like `BoutOptionsValue` which has `__int__()`, `__float__()`, `__str__()` and `__bool__()` methods it would prevent anyone from forgetting to convert (but would be a breaking change). On balance though, I think the current design is more convenient and less surprising for users.

**Comment by bendudson** [comment]
On the BOUT++ default behaviour: It might be good to be more  strict in converting to bool. I agree that converting "foo" to bool should probably raise an error

**Comment by johnomotani** [comment]
> On the BOUT++ default behaviour: It might be good to be more strict in converting to bool. I agree that converting "foo" to bool should probably raise an error

Sounds like a good idea to me, and in keeping with making the `Options` more strict generally. I can make a PR. How about
* `y`, `yes`, `t`, `true` or `1` for true
* `n`, `no`, `f`, `false` or `0` for false
and all case-insensitive? I'd be happy with reducing even further. I tend to always use only `true` and `false` myself...

**Comment by dschwoerer** [comment]
I think as an option we could start with introducing the 
`BoutOptionsValue` type with the methods now, and maybe later stop the 
default conversion. That would not require an extra `as_bool()` but a 
simple `bool()` would suffice, which I think would be cleaner, but 
slightly less obvious, as a normal string would return True, but would 
also work if used in an if statement without extra as_bool ...

I do agree that the breaking change would be an issue ...
