### ISSUE TITLE
Automatic generation of python package on new release

### ISSUE THREAD

**Issue by loeiten** [boutproject/boutdata#4]
I've set up a GitHub Action for automatic python publishing whenever a release is created. However, I do not have the repository permission to add `PYPI_USERNAME` and `PYPI_PASSWORD` to the repository secrets. Is this something you could fix @bendudson?

**Comment by johnomotani** [comment]
@loeiten @ZedThree did we ever resolve this? I'd like to make a new release so I can make a new release of `xBOUT`, which would depend on the new `BoutOptions.__eq__()`.

**Comment by loeiten** [comment]
It's not resolved. Until we can add secrets I guess we have to do it manually.
I've added you as an owner to the pypi project @johnomotani. I can give you rights as well I case you have a user at pypi.org @ZedThree

**Comment by johnomotani** [comment]
Hi @loeiten @ZedThree - can we make @loeiten a maintainer on here so he can add the pypi secrets? It'd be nice to put out a new release with all the recent fixes. Thanks!

**Comment by ZedThree** [comment]
Added as maintainer -- is that sufficient access, or do you need to be admin?

**Comment by loeiten** [comment]
Looks like only [owners and admins](https://docs.github.com/en/free-pro-team@latest/actions/reference/encrypted-secrets#creating-encrypted-secrets-for-a-repository) can make secrets.

Would it be an idea to make a `boutproject` user which maintains the packages at `pypi` (the same goes for `docker hub` etc.)? This way one would not be dependent on a specific user's password as a secret.

**Comment by ZedThree** [comment]
Ok, switched you to admin.

That does sound like a nice solution, but I'd be worried we then just move the problem somewhere else -- how do we maintain access to that account? As long as we can have multiple maintainers on a pypi package, that's probably sufficient.

Speaking of which, please can you add me as maintainer on the boututils/boutdata packages? My pypi username is "yossarian", email address is my York account.

**Comment by loeiten** [comment]
Great, thanks.

I can setup an action as soon as I get some time 🙂. I can do the same for the `boututils` package as well if you would like to (but it look like I would need some new privileges there as well).

I've also added you as an owner of the pypi packages.

**Comment by loeiten** [comment]
I've now created a PR which solves the issue. I could do the same for `boututils` if given permissions

**Comment by bendudson** [comment]
Thanks @loeiten ! I've changed your permissions in `boututils`. Merry Christmas!

**Comment by loeiten** [comment]
Thank you @bendudson. I will make a PR on `boututils` as well then. Merry Christmas to you too 😃🎅
