### ISSUE TITLE
No support for new Hermes-3 input style

### ISSUE THREAD

**Issue by mikekryjak** [boutproject/boutdata#73]
Hermes-3 features species options in the below format:

```
type = (evolve_density, evolve_momentum, evolve_pressure,
        noflow_boundary
)
```

BoutData does not interpret the brackets correctly. The expected behaviour would be for it to read the options in the following hierarchy:

- [species][type][evolve_density]
- [species][type][evolve_pressure]
- ...

Instead, it does the following:

- [species][type][(evolve_density]
- [species][type][evolve_momentum]
- ...
- [species][noflow_boundary)]

It looks like it interprets the brackets as part of the option string and doesn't consider the bracket contents as children of the same option header.

**Comment by johnomotani** [comment]
@mikekryjak could you include a MWE in this issue please (i.e. BOUT.inp and python script that fails to read it properly)?
